// Scenario library – sports, casual, family, etc. Prompts for image gen & img2vid
module.exports = [
  { id: 'beach', name: 'Beach', category: 'casual', icon: '🏖️',
    imagePrompt: 'Same person at a sunny beach, relaxed pose, ocean background, natural lighting, candid vacation photo.',
    videoPrompt: 'The person walks slowly along the beach, waves gently rolling in the background, wind in their hair, golden hour lighting.' },
  { id: 'pool', name: 'Pool', category: 'casual', icon: '🏊',
    imagePrompt: 'Same person by a swimming pool, relaxed summer vibe, poolside lounge or dipping feet, natural light.',
    videoPrompt: 'The person sits by the pool edge, feet in water, slight natural movement, sunlight reflecting on water.' },
  { id: 'gym', name: 'Gym', category: 'sports', icon: '💪',
    imagePrompt: 'Same person in a modern gym, athletic wear, confident pose, fitness environment, professional lighting.',
    videoPrompt: 'The person performs a light workout motion, natural gym setting, subtle movement, motivated energy.' },
  { id: 'yoga', name: 'Yoga', category: 'sports', icon: '🧘',
    imagePrompt: 'Same person in a yoga pose, serene setting, flexible and relaxed, soft natural lighting.',
    videoPrompt: 'The person flows through a gentle yoga movement, calm and fluid, peaceful atmosphere.' },
  { id: 'running', name: 'Running', category: 'sports', icon: '🏃',
    imagePrompt: 'Same person running outdoors, athletic, park or trail background, dynamic energy, natural light.',
    videoPrompt: 'The person runs at a steady pace, outdoor trail or park, natural motion, wind in hair.' },
  { id: 'tennis', name: 'Tennis', category: 'sports', icon: '🎾',
    imagePrompt: 'Same person on a tennis court, athletic outfit, racket in hand, confident stance.',
    videoPrompt: 'The person swings a tennis racket, court in background, fluid athletic motion.' },
  { id: 'family-dinner', name: 'Family Dinner', category: 'family', icon: '🍽️',
    imagePrompt: 'Same person at a family dinner table, warm setting, relaxed smile, casual home environment.',
    videoPrompt: 'The person at a dinner table, slight natural movement, warm family atmosphere, candid moment.' },
  { id: 'garden', name: 'Garden', category: 'family', icon: '🌿',
    imagePrompt: 'Same person in a peaceful garden, flowers or greenery, relaxed outdoor family vibe.',
    videoPrompt: 'The person stands in a garden, gentle breeze moving hair, birds, peaceful moment.' },
  { id: 'wedding', name: 'Wedding', category: 'family', icon: '💒',
    imagePrompt: 'Same person at a wedding, elegant attire, romantic setting, professional portrait quality.',
    videoPrompt: 'The person at a wedding venue, gentle movement, elegant and romantic atmosphere.' },
  { id: 'birthday', name: 'Birthday', category: 'family', icon: '🎂',
    imagePrompt: 'Same person at a birthday celebration, festive, cake or balloons, joyful atmosphere.',
    videoPrompt: 'The person celebrates, slight movement, party atmosphere, warm candid moment.' },
  { id: 'red-carpet', name: 'Red Carpet', category: 'professional', icon: '🌟',
    imagePrompt: 'Same person on a red carpet, formal attire, paparazzi lights, celebrity event.',
    videoPrompt: 'The person walks the red carpet, cameras flashing, confident stride, glamorous.' },
  { id: 'studio', name: 'Studio Portrait', category: 'professional', icon: '📸',
    imagePrompt: 'Same person in a professional photo studio, soft lighting, high-end portrait.',
    videoPrompt: 'The person in a studio, subtle pose change, professional lighting, magazine quality.' },
  { id: 'coffee-shop', name: 'Coffee Shop', category: 'casual', icon: '☕',
    imagePrompt: 'Same person in a cozy coffee shop, casual and relaxed, warm ambiance.',
    videoPrompt: 'The person at a café table, sipping coffee, relaxed natural movement.' },
  { id: 'rooftop', name: 'Rooftop', category: 'casual', icon: '🌆',
    imagePrompt: 'Same person on a city rooftop at golden hour, urban skyline, stylish casual.',
    videoPrompt: 'The person on a rooftop, city lights in background, gentle wind, cinematic.' },
  { id: 'spa', name: 'Spa', category: 'wellness', icon: '💆',
    imagePrompt: 'Same person in a luxury spa setting, relaxed and serene, soft lighting.',
    videoPrompt: 'The person in a spa, relaxed breathing, peaceful, wellness atmosphere.' },
  { id: 'ski', name: 'Ski Slopes', category: 'sports', icon: '⛷️',
    imagePrompt: 'Same person on ski slopes, winter gear, mountain background, adventurous.',
    videoPrompt: 'The person on skis, gentle slope, snow and mountains, winter sport vibe.' },
  { id: 'concert', name: 'Concert', category: 'casual', icon: '🎵',
    imagePrompt: 'Same person at a concert, energetic atmosphere, stage lights, live music vibe.',
    videoPrompt: 'The person at a concert, crowd and lights, natural concert energy.' },
  { id: 'art-gallery', name: 'Art Gallery', category: 'professional', icon: '🖼️',
    imagePrompt: 'Same person in an art gallery, cultured and sophisticated, artwork in background.',
    videoPrompt: 'The person walks through a gallery, viewing art, refined movement.' },
  // Action movie star
  { id: 'action-hero', name: 'Action Hero', category: 'action', icon: '💥',
    imagePrompt: 'Same person as Hollywood action movie star, dynamic pose, dramatic lighting, blockbuster movie poster style, confident and powerful.',
    videoPrompt: 'The person in an action movie scene, dramatic movement, explosive energy, cinematic blockbuster quality.' },
  { id: 'movie-poster', name: 'Movie Poster', category: 'action', icon: '🎬',
    imagePrompt: 'Same person as movie poster star, bold composition, cinematic lighting, Hollywood blockbuster poster style, dramatic and heroic.',
    videoPrompt: 'The person in a movie-style scene, slow dramatic reveal, cinematic lighting, blockbuster production value.' },
  { id: 'spy', name: 'Secret Agent', category: 'action', icon: '🕵️',
    imagePrompt: 'Same person as suave secret agent, sleek suit, mysterious atmosphere, spy thriller movie aesthetic, confident and dangerous.',
    videoPrompt: 'The person in a spy thriller scene, cool demeanor, dramatic shadows, James Bond style atmosphere.' },
  { id: 'superhero', name: 'Superhero', category: 'action', icon: '🦸',
    imagePrompt: 'Same person as superhero, heroic pose, dynamic composition, comic book movie style, powerful and iconic.',
    videoPrompt: 'The person in a superhero-style scene, heroic stance, dramatic lighting, cinematic comic book aesthetic.' },
  // Romance / Boudoir (tasteful artistic)
  { id: 'boudoir', name: 'Boudoir', category: 'romance', icon: '🌹',
    imagePrompt: 'Same person in elegant boudoir portrait, soft romantic lighting, tasteful intimate setting, luxury silk and lace, artistic and sensual.',
    videoPrompt: 'The person in a boudoir setting, gentle movement, soft lighting, romantic and elegant atmosphere.' },
  { id: 'sensual', name: 'Sensual Portrait', category: 'romance', icon: '✨',
    imagePrompt: 'Same person in sensual artistic portrait, soft diffused lighting, romantic mood, tasteful and alluring, high fashion editorial style.',
    videoPrompt: 'The person in a sensual scene, subtle movement, soft romantic lighting, artistic and elegant.' },
  { id: 'romantic', name: 'Romantic', category: 'romance', icon: '💋',
    imagePrompt: 'Same person in romantic intimate portrait, candlelight, soft shadows, passionate and tender mood, artistic photography.',
    videoPrompt: 'The person in a romantic scene, intimate atmosphere, soft warm lighting, tender and elegant.' },
];
